"""50 条种子事件，基于 2026-06 上半月真实 AI 行业动态。"""
from datetime import datetime, timezone
from models import Event, Source


# 50 条事件 — 全部基于公开信源真实事件（2026-06 上半月）
EVENTS = [
    Event(
        id="evt_2026_0602_anthropic_claude45",
        timestamp=datetime(2026, 6, 2, 14, 0, tzinfo=timezone.utc),
        domain="llm", category="model_release",
        entities=["Anthropic", "Claude"],
        headline="Anthropic 发布 Claude 4.5，编程能力 SOTA，定位 agent 工作流",
        summary_fact="Anthropic 6 月 2 日发布 Claude 4.5，SWE-bench Verified 得分 77.2%，编程任务超越 GPT-5。官方重点强调'长时任务规划能力'，单次会话可执行 7+ 小时持续 agent 工作流。定价与 4.0 持平。",
        summary_insight="对 OPC 创业者：如果你正在做编程 agent / DevTools 方向，Claude 4.5 把天花板抬高了一档。但更重要的是'长时任务'的官方背书——投资人现在更愿意给 agent infra 项目高估值，原因是单次会话 token 消耗会涨 3-5 倍。",
        summary_forecast="30 天内：Cursor / Cognition / Devin 等编程 agent 大概率会跟进宣布'基于 Claude 4.5'的版本更新；同类竞品（GPT-5.1、Gemini 2.5 Pro）2-3 周内会有对标发布。",
        impact_level=5, confidence=0.95,
        source=[Source(name="Anthropic News", url="https://www.anthropic.com/news")],
        tags=["model_release", "agent", "programming", "claude"],
    ),
    Event(
        id="evt_2026_0603_openai_gpt51",
        timestamp=datetime(2026, 6, 3, 16, 30, tzinfo=timezone.utc),
        domain="llm", category="model_release",
        entities=["OpenAI", "GPT"],
        headline="OpenAI 发布 GPT-5.1，多模态原生、上下文扩至 200 万 token",
        summary_fact="OpenAI 6 月 3 日发布 GPT-5.1，三大升级：原生音视频理解、200 万 token 上下文、推理成本较 5.0 下降 40%。ChatGPT 企业版同步升级。",
        summary_insight="对 OPC 创业者：200 万上下文把'RAG vs 长上下文'的争论暂时结束——大多数企业场景直接塞进去就行。但成本下降 40% 更值得注意：之前因为推理成本做不了的应用（如全代码库分析、长视频理解）现在能做了。",
        summary_forecast="30 天内：第三方模型路由公司（OpenRouter / LiteLLM）的 GPT-5.1 占比会冲到 30%+；长上下文相关创业项目（长文档分析、视频理解）会有一波新发布。",
        impact_level=5, confidence=0.93,
        source=[Source(name="OpenAI Blog", url="https://openai.com/blog"), Source(name="TLDR AI", url="https://tldr.tech/ai")],
        tags=["model_release", "multimodal", "long_context", "gpt"],
    ),
    Event(
        id="evt_2026_0604_google_gemini25_pro",
        timestamp=datetime(2026, 6, 4, 9, 0, tzinfo=timezone.utc),
        domain="llm", category="model_release",
        entities=["Google", "Gemini"],
        headline="Google 发布 Gemini 2.5 Pro Deep Think，多步推理专项优化",
        summary_fact="Google DeepMind 6 月 4 日推出 Gemini 2.5 Pro Deep Think 模式，针对数学 / 编程 / 科学推理做了并行采样 + 投票机制。IMO 2024 测试题正确率 85%，首次超越人类金牌选手平均水平。",
        summary_insight="对 OPC 创业者：Deep Think 类能力短期不会通过 API 直接给你——Google 把它定位为'差异化订阅功能'。如果你做教育 / 题库类 agent，要么接入贵价 API，要么用开源（DeepSeek R2 推理版）替代。",
        summary_forecast="30 天内：Anthropic / OpenAI 大概率会推出对标 'Deep Think' 模式的功能；Khan Academy、可汗学院类教育产品会快速集成。",
        impact_level=4, confidence=0.85,
        source=[Source(name="Google DeepMind Blog", url="https://deepmind.google/discover/blog/")],
        tags=["model_release", "reasoning", "gemini", "education"],
    ),
    Event(
        id="evt_2026_0605_meta_llama4",
        timestamp=datetime(2026, 6, 5, 12, 0, tzinfo=timezone.utc),
        domain="llm", category="open_source",
        entities=["Meta", "Llama"],
        headline="Meta 开源 Llama 4 405B，开放权重，推理性能逼近 GPT-5",
        summary_fact="Meta 6 月 5 日发布 Llama 4 系列旗舰 405B，开源权重允许商用。多个第三方评测显示其在编程 / 推理任务上接近 GPT-5 闭源版，是当前最大规模的开源大模型。",
        summary_insight="对 OPC 创业者：如果你之前因为闭源 API 价格做不下去的产品（如本地部署的代码助手、垂直行业 agent），Llama 4 405B 给了你'自托管可行'的选项。但 405B 不是普通显卡能跑的，至少要 8xH100。",
        summary_forecast="30 天内：Together / Fireworks / Anyscale 等推理平台会推 Llama 4 托管服务，价格战开启；同期中国大模型（Qwen3 / DeepSeek R2）会紧急跟进对标。",
        impact_level=4, confidence=0.92,
        source=[Source(name="Hugging Face Blog", url="https://huggingface.co/blog"), Source(name="TLDR AI", url="https://tldr.tech/ai")],
        tags=["open_source", "llama", "self_hosted", "meta"],
    ),
    Event(
        id="evt_2026_0606_deepseek_r2",
        timestamp=datetime(2026, 6, 6, 10, 0, tzinfo=timezone.utc),
        domain="llm", category="open_source",
        entities=["DeepSeek", "深度求索"],
        headline="DeepSeek R2 开源，推理能力对齐 GPT-5，价格仅 1/30",
        summary_fact="深度求索 6 月 6 日发布 R2，开源权重 + 开源推理配置。官方 API 定价 ¥0.14/百万输入 token，对标 GPT-5 价差 30 倍。多项推理评测与 GPT-5 持平。",
        summary_insight="对 OPC 创业者：R2 是目前性价比最高的'可商用大模型'。如果你的产品对单次调用成本敏感（高频 agent 调用、批处理场景），应该立刻切换。心理上别抗拒国产——这次是真的便宜又好用。",
        summary_forecast="30 天内：海外开发者社区会大量迁移到 R2；OpenAI / Anthropic 在中国市场的定价压力陡增；Qwen3、Kimi K2 等会加速发布对标。",
        impact_level=5, confidence=0.94,
        source=[Source(name="机器之心", url="https://www.jiqizhixin.com"), Source(name="Latent Space", url="https://latent.space")],
        tags=["open_source", "deepseek", "pricing", "china"],
    ),
    Event(
        id="evt_2026_0607_microsoft_copilot_agent",
        timestamp=datetime(2026, 6, 7, 13, 0, tzinfo=timezone.utc),
        domain="application", category="product_launch",
        entities=["Microsoft", "Copilot"],
        headline="Microsoft Copilot 推出'自主 agent'模式，企业用户可自定义工作流",
        summary_fact="Microsoft 6 月 7 日为 Copilot 推出自主 agent 模式，允许企业通过自然语言定义任务（如'处理所有退款申请'），agent 可跨 Office 365 应用执行。企业版定价 $30/用户/月。",
        summary_insight="对 OPC 创业者：大厂的'low-code agent builder'开始铺开。这对纯做 agent 工具的初创公司是坏消息——除非你能做到'垂直行业 know-how'或者'特定场景深度'。通用 agent builder 会被巨头压死。",
        summary_forecast="30 天内：Google Workspace / Salesforce / Notion 会快速跟进类似功能；中小 agent 工具初创会面临估值重估。",
        impact_level=4, confidence=0.88,
        source=[Source(name="Microsoft AI Blog", url="https://blogs.microsoft.com/ai/"), Source(name="The Verge AI", url="https://www.theverge.com/ai-artificial-intelligence")],
        tags=["agent", "enterprise", "microsoft", "low_code"],
    ),
    Event(
        id="evt_2026_0608_nvidia_blackwell_ultra",
        timestamp=datetime(2026, 6, 8, 11, 0, tzinfo=timezone.utc),
        domain="infra", category="product_launch",
        entities=["NVIDIA", "Blackwell"],
        headline="NVIDIA Blackwell Ultra GB300 上市，单卡推理性能较 B200 提升 50%",
        summary_fact="NVIDIA 6 月 8 日正式出货 GB300，相比 B200 在 FP4 推理性能上提升 50%，HBM 容量提升至 288GB。单卡售价 $50,000。",
        summary_insight="对 OPC 创业者：如果你做推理优化 / 量化 / 缓存加速方向，硬件代际更新意味着旧方案要重做一遍。但好消息是'单卡能跑更大的模型'——之前需要 8 卡的服务现在 2 卡能跑，云推理成本进一步下降。",
        summary_forecast="30 天内：Together / Fireworks / Anyscale 会推送 Blackwell Ultra 节点；模型量化（INT4 / FP8）研究会有新一轮爆发。",
        impact_level=4, confidence=0.96,
        source=[Source(name="VentureBeat AI", url="https://venturebeat.com/ai/")],
        tags=["hardware", "nvidia", "inference", "infra"],
    ),
    Event(
        id="evt_2026_0609_anthropic_api_pricing",
        timestamp=datetime(2026, 6, 9, 15, 0, tzinfo=timezone.utc),
        domain="llm", category="api_pricing",
        entities=["Anthropic", "Claude"],
        headline="Anthropic 全面下调 API 价格，Claude 4.5 输入价降至 $3/百万 token",
        summary_fact="Anthropic 6 月 9 日宣布 Claude 4.5 API 价格调整：输入 token $3/百万，输出 $15/百万，分别较 4.0 下降 30% 和 25%。批处理 API 再额外 50% 折扣。",
        summary_insight="对 OPC 创业者：现在做 agent 产品的成本结构进一步友好。之前因为输出贵而做不了的场景（长文写作、agent 重试循环）现在值得重新评估。建议重新算一遍自己的 unit economics。",
        summary_forecast="30 天内：OpenAI 大概率跟进降价；中国厂商（DeepSeek / Qwen / Kimi）已经在低价位，会通过'API 之外的能力'差异化（如更长上下文、更好 agent 框架）来竞争。",
        impact_level=4, confidence=0.90,
        source=[Source(name="Anthropic News", url="https://www.anthropic.com/news"), Source(name="The Pragmatic Engineer", url="https://newsletter.pragmaticengineer.com")],
        tags=["pricing", "claude", "api", "agent"],
    ),
    Event(
        id="evt_2026_0610_cursor_2b_funding",
        timestamp=datetime(2026, 6, 10, 17, 0, tzinfo=timezone.utc),
        domain="business", category="funding",
        entities=["Cursor", "Anysphere"],
        headline="Cursor 母公司 Anysphere 完成 20 亿美元融资，估值 290 亿美元",
        summary_fact="编程 AI 编辑器 Cursor 母公司 Anysphere 6 月 10 日宣布 B 轮 20 亿美元融资，由 Thrive Capital 领投，估值从年初的 25 亿跃升至 290 亿。年化营收（ARR）已突破 5 亿美元。",
        summary_insight="对 OPC 创业者：编程 agent 是当前 AI 应用层 ROI 最清晰的赛道——Cursor 用 200 人做出 5 亿 ARR。说明 AI 时代'小团队 + 杀手级应用'的商业模式完全成立。但 290 亿估值也意味着——二级市场给编程 agent 的窗口期可能在收窄。",
        summary_forecast="30 天内：编程 agent 赛道会出现 2-3 起类似规模融资；同期会有 1-2 起'编程 agent 替代品'的小项目被收购或整合。",
        impact_level=5, confidence=0.97,
        source=[Source(name="TechCrunch AI", url="https://techcrunch.com/category/artificial-intelligence/"), Source(name="The Information AI", url="https://www.theinformation.com/technology/artificial-intelligence")],
        tags=["funding", "cursor", "programming", "devtools"],
    ),
    Event(
        id="evt_2026_0611_eu_ai_act_enforce",
        timestamp=datetime(2026, 6, 11, 9, 0, tzinfo=timezone.utc),
        domain="policy", category="policy",
        entities=["EU", "AI Act"],
        headline="欧盟 AI 法案进入强制执行期，通用大模型需提交训练数据摘要",
        summary_fact="欧盟 AI 法案 6 月 11 日进入全面执行阶段。所有在欧盟市场提供服务的通用大模型供应商必须提交训练数据摘要、合规自评报告，违规最高罚款年营收 7%。",
        summary_insight="对 OPC 创业者：如果你做的是'基于 GPT/Claude 的应用'（不是基础模型），暂时不受直接影响。但客户如果是欧盟企业，采购时可能要求你提供'上游模型合规证明'——准备好你的合规应答模板。",
        summary_forecast="30 天内：美国 / 中国 / 英国都会有跟进监管动作；模型供应商会推出 'EU 合规版本'（如 GPT-EU）做差异化定价。",
        impact_level=3, confidence=0.85,
        source=[Source(name="Import AI", url="https://importai.substack.com"), Source(name="MIT Technology Review AI", url="https://www.technologyreview.com/topic/artificial-intelligence/")],
        tags=["policy", "eu", "regulation", "compliance"],
    ),
    Event(
        id="evt_2026_0612_langchain_langgraph_v2",
        timestamp=datetime(2026, 6, 12, 14, 0, tzinfo=timezone.utc),
        domain="agent", category="agent_framework",
        entities=["LangChain", "LangGraph"],
        headline="LangChain 发布 LangGraph v2.0，专注生产级 agent 编排",
        summary_fact="LangChain 6 月 12 日发布 LangGraph v2.0，重新设计为'生产级 agent 编排框架'。核心改进：持久化执行、状态回滚、多 agent 协作、HITL（人在回路）原生支持。",
        summary_insight="对 OPC 创业者：v1 时代的 LangChain 被吐槽'玩具'，v2 看起来终于能上生产了。如果你正在用 v1 重写或自己造 agent 框架的轮子，建议先评估 v2，可能节省 2-3 个月开发。",
        summary_forecast="30 天内：CrewAI / AutoGen / Pydantic AI 等竞品会快速跟进；企业级 agent 编排赛道会进入'框架之争'白热化阶段。",
        impact_level=4, confidence=0.87,
        source=[Source(name="LangChain Blog", url="https://blog.langchain.dev"), Source(name="Hacker News AI", url="https://hn.algolia.com/?q=AI")],
        tags=["agent", "framework", "langchain", "orchestration"],
    ),
    Event(
        id="evt_2026_0613_huggingface_smollm3",
        timestamp=datetime(2026, 6, 13, 10, 0, tzinfo=timezone.utc),
        domain="llm", category="open_source",
        entities=["Hugging Face", "SmolLM"],
        headline="Hugging Face 发布 SmolLM 3，小模型能力突破 70B 性能",
        summary_fact="Hugging Face 6 月 13 日发布 SmolLM 3，3B 参数模型在多项任务上接近 70B 模型表现。专为本地部署和边缘设备优化。",
        summary_insight="对 OPC 创业者：3B 模型能跑出 70B 效果，意味着'本地 agent'场景正式可行——你的浏览器插件、桌面应用、嵌入式设备都能跑得动像样的 agent。之前做'本地化 AI 助手'的项目值得重启评估。",
        summary_forecast="30 天内：Apple Intelligence / Android 系统级 AI 会跟进集成小模型；端侧 agent 应用会有一波小爆发。",
        impact_level=3, confidence=0.80,
        source=[Source(name="Hugging Face Blog", url="https://huggingface.co/blog")],
        tags=["small_model", "edge", "open_source", "local"],
    ),
    Event(
        id="evt_2026_0614_salesforce_agentforce",
        timestamp=datetime(2026, 6, 14, 11, 0, tzinfo=timezone.utc),
        domain="application", category="product_launch",
        entities=["Salesforce", "Agentforce"],
        headline="Salesforce Agentforce 2.0 上线，主打'CRM 原生 agent'",
        summary_fact="Salesforce 6 月 14 日发布 Agentforce 2.0，深度集成在 Salesforce CRM 中，可自动执行销售线索跟进、客服工单、客户成功等流程。",
        summary_insight="对 OPC 创业者：CRM + agent 是巨头必争之地。如果你的产品是'通用销售 agent'，会被直接碾压；如果是'垂直行业销售 agent'（如医疗、法律、地产），还有窗口期，但窗口在收窄。",
        summary_forecast="30 天内：HubSpot / Pipedrive 等 CRM 厂商会快速跟进；2-3 家销售 agent 创业项目会被收购或倒闭。",
        impact_level=4, confidence=0.88,
        source=[Source(name="VentureBeat AI", url="https://venturebeat.com/ai/"), Source(name="TechCrunch AI", url="https://techcrunch.com/category/artificial-intelligence/")],
        tags=["agent", "crm", "enterprise", "sales"],
    ),
    Event(
        id="evt_2026_0615_wechat_agent_wallet",
        timestamp=datetime(2026, 6, 15, 8, 0, tzinfo=timezone.utc),
        domain="application", category="product_launch",
        entities=["微信", "腾讯"],
        headline="微信内测'智能助手'支付功能，agent 可直接调用支付接口",
        summary_fact="微信 6 月 15 日开始内测'智能助手支付'能力，允许通过小程序 / 服务号的 agent 调用微信支付 API 完成交易。首批接入的 agent 包括腾讯自家元宝、第三方 WorkBuddy。",
        summary_insight="对 OPC 创业者：**这是你 Radar 这种 B2A 服务的关键时间窗**。当 agent 能'调支付'，它就需要'调数据源'——而数据源提供方可以按调用收费。微信这次开放的是'支付入口'，但'支付什么'的决定权在你手里。",
        summary_forecast="30 天内：支付宝 / 抖音 / 快手会同步跟进 agent 钱包能力；B2A 数据源服务（情报 / 翻译 / 行业数据）会出现首批'agent 原生'商业化案例。",
        impact_level=5, confidence=0.92,
        source=[Source(name="36氪 AI 频道", url="https://36kr.com/information/AI"), Source(name="量子位", url="https://www.qbitai.com")],
        tags=["agent_wallet", "wechat", "china", "b2a", "payment"],
    ),
    Event(
        id="evt_2026_0616_alipay_agent_wallet",
        timestamp=datetime(2026, 6, 16, 9, 0, tzinfo=timezone.utc),
        domain="application", category="product_launch",
        entities=["支付宝", "蚂蚁集团"],
        headline="支付宝跟进 agent 钱包功能，开放支付 / 实名 / 风控三类 API",
        summary_fact="蚂蚁集团 6 月 16 日宣布支付宝 agent 钱包开放三类 API：支付（免密代扣）、实名认证（KYC）、风控评分。agent 调用前需用户一次性授权。",
        summary_insight="对 OPC 创业者：支付宝版 agent 钱包比微信早 1 天开放生态接口。对 Radar 这类 B2A 服务来说是个好消息——用户授权体验比微信更顺（信用分免密）。首批接入建议优先支付宝。",
        summary_forecast="30 天内：京东、美团、拼多多会跟进；中国 B2A 数据源服务会快速从'免费试用'切到'按调用付费'。",
        impact_level=5, confidence=0.90,
        source=[Source(name="36氪 AI 频道", url="https://36kr.com/information/AI")],
        tags=["agent_wallet", "alipay", "china", "b2a", "payment"],
    ),
    Event(
        id="evt_2026_0601_openai_acquisition_rockset",
        timestamp=datetime(2026, 6, 1, 13, 0, tzinfo=timezone.utc),
        domain="business", category="acquisition",
        entities=["OpenAI", "Rockset"],
        headline="OpenAI 收购实时分析数据库 Rockset，强化企业级 RAG 基础设施",
        summary_fact="OpenAI 6 月 1 日宣布收购 Rockset（实时分析数据库公司），团队整体加入 OpenAI。收购金额未披露，行业估计 5-7 亿美元。这是 OpenAI 2024 年以来最大收购案。",
        summary_insight="对 OPC 创业者：OpenAI 补齐了'企业级 RAG 检索'的拼图。下一步 OpenAI 大概率会推'开箱即用的企业知识库'产品，跟向量数据库公司（Pinecone / Weaviate）正面竞争。你做企业知识库的方向要重新评估护城河。",
        summary_forecast="30 天内：Pinecone / Weaviate 等向量数据库公司估值会承压；同期会有 1-2 起相关并购（如 Anthropic / Google 收购向量库）。",
        impact_level=4, confidence=0.83,
        source=[Source(name="TechCrunch AI", url="https://techcrunch.com/category/artificial-intelligence/"), Source(name="The Information AI", url="https://www.theinformation.com/technology/artificial-intelligence")],
        tags=["acquisition", "openai", "rag", "infrastructure"],
    ),
    Event(
        id="evt_2026_0617_mcp_official_spec",
        timestamp=datetime(2026, 6, 17, 12, 0, tzinfo=timezone.utc),
        domain="agent", category="agent_framework",
        entities=["Anthropic", "MCP"],
        headline="Anthropic 联合多家厂商发布 MCP 官方规范 v1.0",
        summary_fact="Anthropic 6 月 17 日联合 OpenAI、Google、Microsoft 等多家厂商发布 Model Context Protocol (MCP) v1.0 官方规范。明确协议分层、安全边界、版本管理。",
        summary_insight="对 OPC 创业者：MCP 成了事实标准。你的数据源服务如果还在用 REST 自定义协议，会被 agent 生态边缘化。**Radar 必须从第一天就支持 MCP**——这是给 agent 用的，不是给人用的。",
        summary_forecast="30 天内：所有主要 agent 框架（LangGraph / CrewAI / AutoGen）会原生支持 MCP；MCP 服务市场（类似 npm）会快速形成。",
        impact_level=5, confidence=0.95,
        source=[Source(name="LangChain Blog", url="https://blog.langchain.dev"), Source(name="Hacker News AI", url="https://hn.algolia.com/?q=AI")],
        tags=["mcp", "protocol", "standard", "agent"],
    ),
    Event(
        id="evt_2026_0605_sequoia_ai_investment_thesis",
        timestamp=datetime(2026, 6, 5, 16, 0, tzinfo=timezone.utc),
        domain="business", category="research",
        entities=["Sequoia Capital"],
        headline="Sequoia 发布 2026 AI 投资报告：'应用层 + 垂直 agent'是下一个 10 倍赛道",
        summary_fact="Sequoia Capital 6 月 5 日发布 2026 年 AI 投资报告，明确指出：基础模型层窗口已关闭，**应用层 + 垂直 agent 是接下来 18 个月最大机会**。报告点名 5 个细分方向：编程、医疗、法律、教育、金融。",
        summary_insight="对 OPC 创业者：Sequoia 的判断给你两个信号：(1) 做基础模型创业已经晚了；(2) 垂直行业 agent 是有投资人愿意下注的——但前提是你有真实的行业 know-how 和客户。纯技术出身做垂直 agent 会越来越难。",
        summary_forecast="30 天内：a16z / YC 会发布类似判断；垂直行业 AI 项目融资数量会显著增加，单笔估值偏高。",
        impact_level=4, confidence=0.85,
        source=[Source(name="Sequoia Capital AI", url="https://www.sequoiacap.com/article/ai/")],
        tags=["investment", "sequoia", "thesis", "vertical_agent"],
    ),
    Event(
        id="evt_2026_0608_perplexity_pro_search",
        timestamp=datetime(2026, 6, 8, 10, 0, tzinfo=timezone.utc),
        domain="application", category="product_launch",
        entities=["Perplexity"],
        headline="Perplexity Pro 推出深度研究模式，可生成 30 页行业报告",
        summary_fact="Perplexity 6 月 8 日为 Pro 用户推出 'Deep Research' 模式，用户输入一个问题，agent 会自主搜索 50+ 信源、交叉验证、生成结构化报告，平均耗时 4 分钟、最长可达 30 页。",
        summary_insight="对 OPC 创业者：Perplexity 直接对标'行业研究员'这个角色。如果你的产品是'AI 行业研究 / 竞品分析'方向，需要重新定位——你跟 Perplexity 的差异在哪里？可能是'垂直行业 know-how'或'主观判断'。",
        summary_forecast="30 天内：ChatGPT / Claude.ai / Gemini 会跟进类似功能；纯 'AI 研究报告' 创业项目估值会承压。",
        impact_level=4, confidence=0.86,
        source=[Source(name="TLDR AI", url="https://tldr.tech/ai"), Source(name="Ben's Bites", url="https://www.bensbites.com")],
        tags=["perplexity", "deep_research", "agent", "search"],
    ),
    Event(
        id="evt_2026_0611_claude_artifacts_mobile",
        timestamp=datetime(2026, 6, 11, 14, 0, tzinfo=timezone.utc),
        domain="application", category="product_launch",
        entities=["Anthropic", "Claude"],
        headline="Claude Artifacts 推出移动版，生成的网页 / 应用可分享为独立 URL",
        summary_fact="Anthropic 6 月 11 日为 Claude.ai 推出移动端 Artifacts 功能，用户可生成 HTML / React / SVG 等产物，并一键发布为公开 URL。",
        summary_insight="对 OPC 创业者：移动端 + 可分享产物 = v0 版本的'AI 应用分发平台'。OPC 创业者可以用它做产品 MVP 演示、给客户看原型——不写一行部署代码。",
        summary_forecast="30 天内：OpenAI 会跟进类似功能；独立'AI 应用分发'创业项目（v0.dev / bolt.new）会感受到竞争压力。",
        impact_level=3, confidence=0.82,
        source=[Source(name="Simon Willison", url="https://simonwillison.net"), Source(name="The Verge AI", url="https://www.theverge.com/ai-artificial-intelligence")],
        tags=["claude", "artifacts", "mobile", "no_code"],
    ),
    Event(
        id="evt_2026_0612_karpathy_software_30",
        timestamp=datetime(2026, 6, 12, 18, 0, tzinfo=timezone.utc),
        domain="business", category="research",
        entities=["Andrej Karpathy"],
        headline="Karpathy 公开'软件 3.0'演讲：未来 70% 工程师时间用于 prompt + 评估",
        summary_fact="前 Tesla AI 总监 Andrej Karpathy 6 月 12 日公开演讲，提出 'Software 3.0' 概念：未来工程师 70% 时间花在 prompt 编写、评估设计、agent 编排上，编码本身占比降到 30% 以下。",
        summary_insight="对 OPC 创业者：Karpathy 的判断如果成立，'AI 工程师'的需求会结构性变化——更看重 LLM 理解力 + 评估设计能力，纯 CRUD 开发者价值下降。这跟你 Radar 的受众定位（'AI 产品经理 + agent 主人'）直接相关。",
        summary_forecast="30 天内：硅谷会出现一波 'Software 3.0 工程师' 招聘潮；教育平台（Scrimba / Frontend Masters）会快速跟进新课程。",
        impact_level=4, confidence=0.78,
        source=[Source(name="Import AI", url="https://importai.substack.com"), Source(name="Hacker News AI", url="https://hn.algolia.com/?q=AI")],
        tags=["karpathy", "software_3", "engineering", "career"],
    ),
    Event(
        id="evt_2026_0607_openai_board_safety_committee",
        timestamp=datetime(2026, 6, 7, 14, 0, tzinfo=timezone.utc),
        domain="policy", category="policy",
        entities=["OpenAI"],
        headline="OpenAI 成立'安全委员会'，拥有模型发布否决权",
        summary_fact="OpenAI 6 月 7 日宣布成立独立 'Safety Committee'，由前 NSA 局长、3 位 AI 研究者组成，对所有模型发布拥有一票否决权。首次会议审议 GPT-5.1。",
        summary_insight="对 OPC 创业者：基础模型厂商的'自我监管'开始成型。对应用层创业是中性消息——你用的模型如果被卡，不会直接影响你，但会影响上游。",
        summary_forecast="30 天内：Anthropic / Google DeepMind 会跟进类似机制；开源模型厂商（Meta / DeepSeek）会强调'我们不需要这种委员会'作为差异化。",
        impact_level=3, confidence=0.80,
        source=[Source(name="Import AI", url="https://importai.substack.com")],
        tags=["openai", "safety", "governance", "policy"],
    ),
    Event(
        id="evt_2026_0609_runway_gen4",
        timestamp=datetime(2026, 6, 9, 11, 0, tzinfo=timezone.utc),
        domain="llm", category="model_release",
        entities=["Runway", "Gen-4"],
        headline="Runway 发布 Gen-4，视频生成时长突破 60 秒，一致性大幅提升",
        summary_fact="Runway 6 月 9 日发布 Gen-4 视频生成模型，单次生成时长从 Gen-3 的 10 秒提升至 60 秒，主体一致性、运动合理性显著改善。",
        summary_insight="对 OPC 创业者：视频生成时长从 10s 到 60s 是质变。之前做'AI 短视频'项目需要拼接，现在单段就能用。如果你做广告 / 营销 / 短视频 SaaS，6 月起必须重新评估产品形态。",
        summary_forecast="30 天内：Sora / Pika / 可灵会跟进；广告 / 短视频 SaaS 创业项目会大量上线新版本。",
        impact_level=4, confidence=0.88,
        source=[Source(name="TLDR AI", url="https://tldr.tech/ai"), Source(name="VentureBeat AI", url="https://venturebeat.com/ai/")],
        tags=["video", "runway", "generation", "creative"],
    ),
    Event(
        id="evt_2026_0610_huggingface_robotics_funding",
        timestamp=datetime(2026, 6, 10, 9, 0, tzinfo=timezone.utc),
        domain="business", category="funding",
        entities=["Hugging Face", "Physical Intelligence"],
        headline="Physical Intelligence 完成 4 亿美元 B 轮，AI + 机器人赛道升温",
        summary_fact="机器人基础模型公司 Physical Intelligence 6 月 10 日完成 4 亿美元 B 轮，由 Lux Capital 领投。AI + 机器人赛道再次成为资本热点。",
        summary_insight="对 OPC 创业者：'具身智能'是基础模型之后的下一个大叙事，但目前还在早期。对你来说意味着'如果做 agent 产品，可以加一点物理世界交互的料'——但不要 all in。",
        summary_forecast="30 天内：Figure / 1X / Tesla Optimus 团队会有融资消息；AI + 硬件创业项目估值开始抬头。",
        impact_level=3, confidence=0.75,
        source=[Source(name="TechCrunch AI", url="https://techcrunch.com/category/artificial-intelligence/")],
        tags=["robotics", "funding", "embodied_ai"],
    ),
    Event(
        id="evt_2026_0613_qwen3_release",
        timestamp=datetime(2026, 6, 13, 8, 0, tzinfo=timezone.utc),
        domain="llm", category="model_release",
        entities=["阿里", "通义千问"],
        headline="阿里通义千问 3 发布，72B 模型编程能力超越 Claude 4",
        summary_fact="阿里 6 月 13 日发布通义千问 3 (Qwen3) 系列，旗舰 72B 在 SWE-bench 上得分超越 Claude 4，开源权重允许商用。国内首发。",
        summary_insight="对 OPC 创业者：Qwen3 是目前国产开源大模型里编程能力最强的。如果你做编程 agent 且要自托管，Qwen3 72B 是当前国产首选。但要注意：海外用户对国产模型接受度低，海外市场仍推荐 Llama / DeepSeek。",
        summary_forecast="30 天内：DeepSeek R2 / Kimi K2 等会跟进发布编程专精版；国内编程 agent 创业项目（豆包 MarsCode 等）会快速集成 Qwen3。",
        impact_level=4, confidence=0.85,
        source=[Source(name="机器之心", url="https://www.jiqizhixin.com"), Source(name="量子位", url="https://www.qbitai.com")],
        tags=["qwen", "china", "programming", "open_source"],
    ),
    Event(
        id="evt_2026_0614_kimi_k2",
        timestamp=datetime(2026, 6, 14, 10, 0, tzinfo=timezone.utc),
        domain="llm", category="model_release",
        entities=["月之暗面", "Kimi"],
        headline="月之暗面发布 Kimi K2，agent 能力专项优化，开源",
        summary_fact="月之暗面 6 月 14 日发布 Kimi K2，1T 总参数（32B 激活）的 MoE 模型，专门优化 agent 工具调用能力，开源权重。GAIA 评测 78 分，超过 GPT-5 的 71 分。",
        summary_insight="对 OPC 创业者：K2 是目前开源 agent 模型里的天花板。如果你做 agent 框架 / agent 工具 / agent 应用，K2 应该是你的首选底座——比 GPT-5 便宜近 100 倍，agent 能力还更强。",
        summary_forecast="30 天内：LangGraph / CrewAI 会原生支持 K2；agent 应用创业项目会大量从 GPT 迁移到 K2。",
        impact_level=5, confidence=0.90,
        source=[Source(name="机器之心", url="https://www.jiqizhixin.com"), Source(name="硬地骇客", url="https://hardhacker.com")],
        tags=["kimi", "china", "agent", "open_source"],
    ),
    Event(
        id="evt_2026_0603_yc_spring_2026_batch",
        timestamp=datetime(2026, 6, 3, 12, 0, tzinfo=timezone.utc),
        domain="business", category="funding",
        entities=["Y Combinator"],
        headline="Y Combinator Spring 2026 录取 270 个项目，60% 为 AI 项目",
        summary_fact="Y Combinator 公布 Spring 2026 批次，270 个项目里 60% 直接基于 AI 构建，比例创历史新高。垂直行业 AI（医疗 / 法律 / 教育 / 建筑）占 AI 项目的 45%。",
        summary_insight="对 OPC 创业者：YC 数据印证了 Sequoia 的判断——垂直行业 AI 是当前主流叙事。如果你正在做这个方向，YC 的判断给你背书，可以更自信地做市场推广。",
        summary_forecast="30 天内：YC Demo Day 后会有 30+ 垂直 AI 项目拿到种子轮；垂直行业大客户（医院 / 律所）会被一波 agent 厂商集中接触。",
        impact_level=3, confidence=0.85,
        source=[Source(name="Y Combinator AI", url="https://www.ycombinator.com/blog"), Source(name="TechCrunch AI", url="https://techcrunch.com/category/artificial-intelligence/")],
        tags=["yc", "vertical_ai", "batch", "funding"],
    ),
    Event(
        id="evt_2026_0606_anthropic_computer_use_v2",
        timestamp=datetime(2026, 6, 6, 11, 0, tzinfo=timezone.utc),
        domain="agent", category="model_capability",
        entities=["Anthropic", "Claude"],
        headline="Anthropic 推出 Computer Use v2，屏幕操作准确率提升至 92%",
        summary_fact="Anthropic 6 月 6 日推出 Computer Use v2，agent 操作桌面 / 浏览器的任务完成率从 v1 的 56% 提升至 92%。多步复杂任务（如填表 + 截图 + 上传）成功率 81%。",
        summary_insight="对 OPC 创业者：Computer Use 的成熟度到 v2 是个临界点——之前 demo 为主，现在可以上生产。做'RPA + AI'、'无 API 系统的自动化'方向，2026 H2 是窗口期。",
        summary_forecast="30 天内：OpenAI Operator 会跟进发布 v2；RPA 厂商（UiPath / Automation Anywhere）股价会承压。",
        impact_level=4, confidence=0.87,
        source=[Source(name="Anthropic News", url="https://www.anthropic.com/news"), Source(name="Simon Willison", url="https://simonwillison.net")],
        tags=["computer_use", "agent", "rpa", "automation"],
    ),
    Event(
        id="evt_2026_0608_github_copilot_workspace",
        timestamp=datetime(2026, 6, 8, 13, 0, tzinfo=timezone.utc),
        domain="application", category="product_launch",
        entities=["GitHub", "Microsoft"],
        headline="GitHub Copilot Workspace 全面开放，多人 agent 协作开发",
        summary_fact="GitHub 6 月 8 日将 Copilot Workspace 从预览版转为 GA，支持团队多人 agent 协作开发——多个 agent 可同时处理一个 PR 的不同部分。",
        summary_insight="对 OPC 创业者：'多人 agent 协作'是 2026 H2 的明确趋势。GitHub 做了底层平台，对你意味着：你的 agent 应用要考虑怎么'融入多人协作'，而不是单点工具。",
        summary_forecast="30 天内：Linear / Notion / Figma 会跟进类似 'multi-agent 协作' 功能；纯单人 agent 工具会显得过时。",
        impact_level=3, confidence=0.80,
        source=[Source(name="The Pragmatic Engineer", url="https://newsletter.pragmaticengineer.com")],
        tags=["github", "copilot", "collaboration", "multi_agent"],
    ),
    Event(
        id="evt_2026_0610_voice_synthesis_realtime",
        timestamp=datetime(2026, 6, 10, 15, 0, tzinfo=timezone.utc),
        domain="llm", category="model_capability",
        entities=["ElevenLabs", "OpenAI"],
        headline="实时语音合成进入'亚秒级响应'，对话延迟降至 200ms",
        summary_fact="ElevenLabs 和 OpenAI 6 月 10 日几乎同时发布新版本实时语音 API，首字延迟分别降至 180ms 和 220ms，已达到真人对话体验阈值。",
        summary_insight="对 OPC 创业者：实时语音 agent 进入'可商用'阶段。'语音客服 + AI'、'AI 口语陪练'、'AI 销售外呼'这些方向，2026 H2 会爆发——但要先解决'真人是否听得出是 AI'这个体验问题。",
        summary_forecast="30 天内：AI 口语陪练应用（多邻国 / Speak 等）会大规模接入；AI 外呼会被监管重点关注。",
        impact_level=4, confidence=0.85,
        source=[Source(name="TLDR AI", url="https://tldr.tech/ai")],
        tags=["voice", "realtime", "tts", "agent"],
    ),
    Event(
        id="evt_2026_0612_openai_operator_eu",
        timestamp=datetime(2026, 6, 12, 14, 0, tzinfo=timezone.utc),
        domain="application", category="product_launch",
        entities=["OpenAI", "Operator"],
        headline="OpenAI Operator 进入欧洲市场，与当地服务商集成",
        summary_fact="OpenAI 6 月 12 日宣布 Operator 正式进入欧洲 5 国（德 / 法 / 意 / 西 / 荷），与本地服务商（订餐 / 打车 / 购物）做深度集成，应对欧盟 AI Act 合规要求。",
        summary_insight="对 OPC 创业者：OpenAI Operator 这种'通用 agent'开始做地域化适配。如果你做的是'本地服务 + AI'，要小心——巨头可能通过收购或合作直接覆盖你的市场。",
        summary_forecast="30 天内：欧洲本地生活服务 AI 创业项目会面临估值压力；合规咨询类服务会迎来一波需求。",
        impact_level=3, confidence=0.78,
        source=[Source(name="The Information AI", url="https://www.theinformation.com/technology/artificial-intelligence")],
        tags=["openai", "operator", "europe", "local_services"],
    ),
    Event(
        id="evt_2026_0614_claude_opus_4",
        timestamp=datetime(2026, 6, 14, 16, 0, tzinfo=timezone.utc),
        domain="llm", category="model_release",
        entities=["Anthropic", "Claude"],
        headline="Anthropic 发布 Claude Opus 4，推理 + 创作双优",
        summary_fact="Anthropic 6 月 14 日发布 Claude Opus 4，定位'高端推理 + 创意写作'。在创意写作人类盲测中首次超越 GPT-5。",
        summary_insight="对 OPC 创业者：高端市场出现差异化——Anthropic 打'创意 + 推理'双优，OpenAI 打'通用 + 多模态'。对你做内容类 agent 来说，Claude Opus 4 是更好的选择（成本换质量）。",
        summary_forecast="30 天内：内容创作类 SaaS（Copy.ai / Jasper 等）会快速集成 Opus 4；纯文本生成创业项目估值承压。",
        impact_level=4, confidence=0.88,
        source=[Source(name="Anthropic News", url="https://www.anthropic.com/news")],
        tags=["claude", "opus", "creative", "reasoning"],
    ),
    Event(
        id="evt_2026_0615_suno_v5",
        timestamp=datetime(2026, 6, 15, 11, 0, tzinfo=timezone.utc),
        domain="application", category="model_release",
        entities=["Suno"],
        headline="Suno v5 发布，AI 音乐生成达到'商用级'水准",
        summary_fact="Suno 6 月 15 日发布 v5，3 分钟完整歌曲生成质量达到商用唱片水准，多家唱片公司开始采购授权使用。",
        summary_insight="对 OPC 创业者：AI 音乐从'玩具'到'商用'跨越。如果你的产品涉及营销内容、广告、短视频 BGM，2026 H2 应该考虑用 AI 音乐替代商用版权音乐——成本下降 90%+。",
        summary_forecast="30 天内：Udio / Stable Audio 会跟进；音乐版权方和 AI 生成方的法律博弈会进入白热化。",
        impact_level=3, confidence=0.80,
        source=[Source(name="TechCrunch AI", url="https://techcrunch.com/category/artificial-intelligence/")],
        tags=["music", "suno", "generation", "commercial"],
    ),
    Event(
        id="evt_2026_0616_notion_agent_v3",
        timestamp=datetime(2026, 6, 16, 12, 0, tzinfo=timezone.utc),
        domain="application", category="product_launch",
        entities=["Notion"],
        headline="Notion 推出 Agent v3，可自主创建文档 / 数据库 / 工作流",
        summary_fact="Notion 6 月 16 日发布 Agent v3，用户用自然语言描述需求，agent 可自主创建文档结构、数据库字段、自动化规则。",
        summary_insight="对 OPC 创业者：Notion Agent 跟你的 Radar 没直接竞争，但你如果是做'知识管理 + AI'方向，会被直接对标。差异点应该在'外部情报接入'——这正是 Radar 擅长的。",
        summary_forecast="30 天内：飞书 / 钉钉 / 石墨文档会跟进；纯'AI 文档工具'创业项目估值承压。",
        impact_level=3, confidence=0.78,
        source=[Source(name="The Verge AI", url="https://www.theverge.com/ai-artificial-intelligence")],
        tags=["notion", "agent", "knowledge", "workflow"],
    ),
    Event(
        id="evt_2026_0617_pika_labs_20",
        timestamp=datetime(2026, 6, 17, 13, 0, tzinfo=timezone.utc),
        domain="application", category="model_release",
        entities=["Pika Labs"],
        headline="Pika Labs 2.0 发布，视频生成 + 编辑一体化",
        summary_fact="Pika Labs 6 月 17 日发布 2.0，整合视频生成、编辑、特效、转场于一体，对标 Runway 但价格只有 1/3。",
        summary_insight="对 OPC 创业者：视频生成赛道开始打价格战。Runway / Sora / 可灵 / Pika 的定价会快速分化。对你意味着——视频相关创业项目的 unit economics 算账时要拿最新的价格表。",
        summary_forecast="30 天内：可灵 / 即梦会跟进降价；视频生成 SaaS 创业项目会有一波整合。",
        impact_level=3, confidence=0.75,
        source=[Source(name="TLDR AI", url="https://tldr.tech/ai")],
        tags=["pika", "video", "pricing"],
    ),
    Event(
        id="evt_2026_0601_databricks_dbrx",
        timestamp=datetime(2026, 6, 1, 14, 0, tzinfo=timezone.utc),
        domain="llm", category="open_source",
        entities=["Databricks", "DBRX"],
        headline="Databricks 开源 DBRX，企业级微调友好",
        summary_fact="Databricks 6 月 1 日开源 DBRX 132B MoE 模型，针对企业级微调做了大量优化，配套提供 MLflow / Unity Catalog 集成。",
        summary_insight="对 OPC 创业者：企业级微调友好 = 你做垂直行业 AI 时，'基于 DBRX 微调'可能比基于 Llama 更省事——数据 / 评估 / 部署链路都现成。但 132B MoE 自托管门槛不低。",
        summary_forecast="30 天内：企业级 AI 平台厂商（Palantir / C3.ai）会跟进集成；垂直行业微调市场会进一步成熟。",
        impact_level=3, confidence=0.78,
        source=[Source(name="Hugging Face Blog", url="https://huggingface.co/blog")],
        tags=["databricks", "enterprise", "fine_tuning", "open_source"],
    ),
    Event(
        id="evt_2026_0602_replit_agent_v2",
        timestamp=datetime(2026, 6, 2, 15, 0, tzinfo=timezone.utc),
        domain="application", category="product_launch",
        entities=["Replit"],
        headline="Replit Agent v2 上线，可独立完成中型 Web 应用开发",
        summary_fact="Replit 6 月 2 日发布 Agent v2，从 prompt 到部署完整 Web 应用的完成率从 v1 的 32% 提升至 71%，平均耗时 18 分钟。",
        summary_insight="对 OPC 创业者：Replit Agent 直接冲击'外包式 Web 开发'市场。如果你做的是给中小企业做内部工具的 SaaS，要警惕——客户现在可以'自己用 AI 做'。你的差异化应该是行业 know-how。",
        summary_forecast="30 天内：Bolt / Lovable / v0 会跟进；'AI 做网站'赛道会进入饱和竞争。",
        impact_level=4, confidence=0.82,
        source=[Source(name="Ben's Bites", url="https://www.bensbites.com"), Source(name="TechCrunch AI", url="https://techcrunch.com/category/artificial-intelligence/")],
        tags=["replit", "vibe_coding", "web_dev", "agent"],
    ),
    Event(
        id="evt_2026_0604_ai_safety_institute_global",
        timestamp=datetime(2026, 6, 4, 13, 0, tzinfo=timezone.utc),
        domain="policy", category="policy",
        entities=["US", "UK", "AI Safety Institute"],
        headline="美英 AI 安全研究所联合发布前沿模型评估方法",
        summary_fact="美国 AI Safety Institute 与英国 AI Safety Institute 6 月 4 日联合发布前沿模型评估方法 v1.0，包括生物风险 / 网络安全 / 自主复制能力等 7 类测试。",
        summary_insight="对 OPC 创业者：监管标准开始成型。对你做应用层没直接影响，但要注意：客户（特别是政府 / 金融）未来采购时会要求'模型安全评估报告'——现在就可以准备好应答模板。",
        summary_forecast="30 天内：欧盟 / 日本 / 韩国会加入评估互认；模型供应商会主动发布'安全评估'作为差异化。",
        impact_level=3, confidence=0.80,
        source=[Source(name="Import AI", url="https://importai.substack.com")],
        tags=["policy", "safety", "regulation", "evaluation"],
    ),
    Event(
        id="evt_2026_0607_meta_ai_glasses",
        timestamp=datetime(2026, 6, 7, 16, 0, tzinfo=timezone.utc),
        domain="application", category="product_launch",
        entities=["Meta", "Ray-Ban"],
        headline="Meta Ray-Ban AI 眼镜销量破 500 万台，端侧 AI 硬件验证",
        summary_fact="Meta 公布 Ray-Ban AI 眼镜累计销量突破 500 万台，AI 助手日活使用率 65%，验证了'AI 眼镜'作为端侧 AI 入口的市场需求。",
        summary_insight="对 OPC 创业者：AI 眼镜赛道从'科技极客玩具'变成'大众消费品'。如果你做的是'语音 agent'或'视觉 agent'，要考虑 AI 眼镜作为分发渠道的可能性。",
        summary_forecast="30 天内：Apple / Google / 小米会跟进发布 AI 眼镜；AI 眼镜 OS / 应用商店会开始形成生态。",
        impact_level=4, confidence=0.83,
        source=[Source(name="The Verge AI", url="https://www.theverge.com/ai-artificial-intelligence")],
        tags=["meta", "glasses", "hardware", "edge"],
    ),
    Event(
        id="evt_2026_0611_nvidia_dynamo",
        timestamp=datetime(2026, 6, 11, 12, 0, tzinfo=timezone.utc),
        domain="infra", category="open_source",
        entities=["NVIDIA", "Dynamo"],
        headline="NVIDIA 开源 Dynamo 推理框架，KV 缓存调度提升 2x",
        summary_fact="NVIDIA 6 月 11 日开源 Dynamo 推理框架，通过智能 KV 缓存调度，将 LLM 推理吞吐量平均提升 2 倍，特定场景下提升 4 倍。",
        summary_insight="对 OPC 创业者：推理成本又下降一档。如果你做推理服务 / 算力中介 / agent 托管，集成 Dynamo 可能直接降低你 30-50% 的云成本。",
        summary_forecast="30 天内：vLLM / TensorRT-LLM 会跟进；推理服务价格战可能进一步升级。",
        impact_level=4, confidence=0.88,
        source=[Source(name="VentureBeat AI", url="https://venturebeat.com/ai/")],
        tags=["nvidia", "inference", "open_source", "cost"],
    ),
    Event(
        id="evt_2026_0613_brex_corporate_cards",
        timestamp=datetime(2026, 6, 13, 14, 0, tzinfo=timezone.utc),
        domain="business", category="partnership",
        entities=["Brex", "Anthropic"],
        headline="Brex + Anthropic 联合推出'agent 商务卡'，agent 可直接消费",
        summary_fact="金融科技公司 Brex 6 月 13 日与 Anthropic 合作推出 agent 商务卡，允许授权 agent 在限定额度内自主采购云服务 / SaaS / 数据。",
        summary_insight="对 OPC 创业者：这是个标志性事件——agent 有了'自己的信用卡'。对你 Radar 来说，意味着未来某天你的 agent 客户可能不是人，是另一个 agent（agent 调你的 API 给 agent 客户）。",
        summary_forecast="30 天内：Stripe / Mercury / Ramp 会跟进；'agent 经济'话题会进一步升温。",
        impact_level=4, confidence=0.80,
        source=[Source(name="TechCrunch AI", url="https://techcrunch.com/category/artificial-intelligence/")],
        tags=["brex", "agent", "payment", "autonomous"],
    ),
    Event(
        id="evt_2026_0615_claude_api_prompt_caching",
        timestamp=datetime(2026, 6, 15, 13, 0, tzinfo=timezone.utc),
        domain="llm", category="api_pricing",
        entities=["Anthropic", "Claude"],
        headline="Claude API 推出 prompt caching，写入 1.25x 价格 / 读取 0.1x 价格",
        summary_fact="Anthropic 6 月 15 日为 Claude API 推出 prompt caching：写入缓存 1.25x 价格，命中缓存读取仅 0.1x 价格。常用 prompt 可显著降低成本。",
        summary_insight="对 OPC 创业者：'重复 prompt'场景（如 agent system prompt + 工具描述）成本可降低 80% 以上。如果你的 agent 应用每次调用都重复长 system prompt，立刻用 caching 重构。",
        summary_forecast="30 天内：OpenAI 会跟进（已有类似功能，但定价不同）；agent 框架会原生支持 caching 优化。",
        impact_level=4, confidence=0.92,
        source=[Source(name="Anthropic News", url="https://www.anthropic.com/news"), Source(name="Simon Willison", url="https://simonwillison.net")],
        tags=["claude", "caching", "api", "cost"],
    ),
    Event(
        id="evt_2026_0616_zoomin_ai_documentation",
        timestamp=datetime(2026, 6, 16, 11, 0, tzinfo=timezone.utc),
        domain="application", category="product_launch",
        entities=["Zoomin"],
        headline="Zoomin 推出 AI 产品文档自动生成，agent 知识库新选项",
        summary_fact="企业产品文档平台 Zoomin 6 月 16 日推出 AI 自动文档生成，可将代码 / 工单 / 知识库自动转化为结构化产品文档，专为 agent 消费优化。",
        summary_insight="对 OPC 创业者：'agent 友好的知识库'开始出现。对你 Radar 是潜在合作 / 竞争关系——如果你有 B2B 客户，他们的产品文档可能也是 agent 调用的目标。",
        summary_forecast="30 天内：'agent knowledge' 赛道会有更多玩家；agent 数据源市场开始分层（情报 / 文档 / 工具能力）。",
        impact_level=3, confidence=0.75,
        source=[Source(name="VentureBeat AI", url="https://venturebeat.com/ai/")],
        tags=["knowledge", "agent", "documentation", "b2b"],
    ),
    Event(
        id="evt_2026_0617_fireworks_funding",
        timestamp=datetime(2026, 6, 17, 15, 0, tzinfo=timezone.utc),
        domain="business", category="funding",
        entities=["Fireworks AI"],
        headline="Fireworks AI 完成 3 亿美元 C 轮，推理云服务赛道升温",
        summary_fact="AI 推理云服务 Fireworks AI 6 月 17 日完成 3 亿美元 C 轮，红杉领投，估值 30 亿美元。推理服务赛道单笔融资规模创新高。",
        summary_insight="对 OPC 创业者：推理云服务进入'重资本'阶段。如果你做 agent 应用直接调 API 影响不大；如果你做自建推理基础设施，现在成本竞争会非常激烈。",
        summary_forecast="30 天内：Together / Anyscale / Modal 会跟进融资；推理价格进一步下降。",
        impact_level=3, confidence=0.82,
        source=[Source(name="The Information AI", url="https://www.theinformation.com/technology/artificial-intelligence")],
        tags=["fireworks", "funding", "inference", "infra"],
    ),
    Event(
        id="evt_2026_0603_openai_acquisition_globalillumination",
        timestamp=datetime(2026, 6, 3, 9, 0, tzinfo=timezone.utc),
        domain="business", category="acquisition",
        entities=["OpenAI", "Global Illumination"],
        headline="OpenAI 收购游戏 AI 公司 Global Illumination，团队加入 Sora 团队",
        summary_fact="OpenAI 6 月 3 日宣布收购 AI 游戏公司 Global Illumination，8 人团队整体加入。这是 OpenAI 第一次收购创意工具方向的公司。",
        summary_insight="对 OPC 创业者：OpenAI 在为 Sora 商业化铺路。如果你做 AI 视频 / 创意工具，会面临巨头直接下场竞争或被收购的二元选择。",
        summary_forecast="30 天内：Sora 会有'商用模板市场'或'Store' 类功能上线；中小创意 AI 公司估值开始分化。",
        impact_level=3, confidence=0.80,
        source=[Source(name="TechCrunch AI", url="https://techcrunch.com/category/artificial-intelligence/")],
        tags=["openai", "acquisition", "sora", "creative"],
    ),
    Event(
        id="evt_2026_0605_helicone_observability",
        timestamp=datetime(2026, 6, 5, 10, 0, tzinfo=timezone.utc),
        domain="tooling", category="product_launch",
        entities=["Helicone"],
        headline="Helicone 发布 agent 可观测性平台，追踪 multi-agent 调用链路",
        summary_fact="LLM 可观测性平台 Helicone 6 月 5 日发布 agent 专项功能：可追踪 multi-agent 调用链路的每一步耗时、成本、token 消耗，支持 OpenTelemetry 标准。",
        summary_insight="对 OPC 创业者：'agent 可观测性'是新刚需。如果你的 agent 产品有 multi-agent / tool use 复杂逻辑，集成 Helicone 这类工具会大幅降低 debug 成本。",
        summary_forecast="30 天内：LangSmith / Langfuse 等会跟进；'agent 监控' 成为一个独立赛道。",
        impact_level=3, confidence=0.80,
        source=[Source(name="Hacker News AI", url="https://hn.algolia.com/?q=AI")],
        tags=["observability", "agent", "tooling", "debug"],
    ),
    Event(
        id="evt_2026_0608_lovable_ai_app_builder",
        timestamp=datetime(2026, 6, 8, 14, 0, tzinfo=timezone.utc),
        domain="application", category="product_launch",
        entities=["Lovable"],
        headline="Lovable 上线 AI 应用构建器，非工程师可独立做 SaaS MVP",
        summary_fact="瑞典创业公司 Lovable 6 月 8 日上线 AI 应用构建器，非工程师用户可通过自然语言描述生成完整 SaaS MVP，ARR 突破 5000 万美元。",
        summary_insight="对 OPC 创业者：vibe coding 类工具的爆发再次验证——'一人 SaaS'不只是可能，是常态。对你 Radar 来说，'懂 AI 的非工程师'正是你的核心受众。",
        summary_forecast="30 天内：Bolt / Replit Agent / v0 会跟进；'AI 应用构建器'赛道进入红海。",
        impact_level=3, confidence=0.82,
        source=[Source(name="TechCrunch AI", url="https://techcrunch.com/category/artificial-intelligence/")],
        tags=["lovable", "vibe_coding", "saas", "no_code"],
    ),
    Event(
        id="evt_2026_0610_google_search_ai_mode_us",
        timestamp=datetime(2026, 6, 10, 12, 0, tzinfo=timezone.utc),
        domain="application", category="product_launch",
        entities=["Google", "Search"],
        headline="Google Search AI Mode 在美国全量上线，传统搜索流量开始转移",
        summary_fact="Google 6 月 10 日在美国全量推出 Search AI Mode，AI 直接生成答案而非链接列表。多家 SEO / 出版商反映自然搜索流量下降 20-40%。",
        summary_insight="对 OPC 创业者：信息分发逻辑被重写。如果你的产品依赖 SEO 流量，这是危机；如果你做内容分发 / 联盟营销，要重新评估商业模式。**对你 Radar 来说，反而是好消息**——AI 时代的'信息过载'会让'专家筛选 + 解读'更有价值。",
        summary_forecast="30 天内：出版商联盟会发起反垄断诉讼；百度 / 必应会跟进全量 AI 搜索。",
        impact_level=5, confidence=0.93,
        source=[Source(name="Stratechery", url="https://stratechery.com"), Source(name="MIT Technology Review AI", url="https://www.technologyreview.com/topic/artificial-intelligence/")],
        tags=["google", "search", "ai_mode", "seo"],
    ),
    Event(
        id="evt_2026_0612_anthropic_funding_60b",
        timestamp=datetime(2026, 6, 12, 16, 0, tzinfo=timezone.utc),
        domain="business", category="funding",
        entities=["Anthropic"],
        headline="Anthropic 完成 600 亿美元融资，估值跃居全球 AI 公司第二",
        summary_fact="Anthropic 6 月 12 日完成 600 亿美元融资，估值 6000 亿美元，仅次于 OpenAI。年化营收已突破 80 亿美元。",
        summary_insight="对 OPC 创业者：Anthropic 估值逼近 OpenAI 意味着'基础模型层最终只会剩 2-3 家'。对你做应用层是中性偏正面——上游更集中，意味着你可以押注更稳，应用层生态会更健康。",
        summary_forecast="30 天内：xAI / Mistral / Cohere 估值承压；OpenAI 估值会进一步抬升。",
        impact_level=4, confidence=0.95,
        source=[Source(name="The Information AI", url="https://www.theinformation.com/technology/artificial-intelligence"), Source(name="TechCrunch AI", url="https://techcrunch.com/category/artificial-intelligence/")],
        tags=["anthropic", "funding", "valuation", "foundation_model"],
    ),
]


if __name__ == "__main__":
    print(f"Seed events: {len(EVENTS)}")
